apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-frontend-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /frontend
      # - path: /?(.*)
        # pathType: ImplementationSpecific
        pathType: Prefix
        backend:
          service:
            name: my-frontend-clusterip-service
            port:
              number: 80
