apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-frontend
  labels:
    app: my-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-frontend
  template:
    metadata:
      labels:
        app: my-frontend
    spec:
      automountServiceAccountToken: false
      containers:
        - name: my-frontend
          image: wxn2001/my-frontend:latest
          ports:
            - containerPort: {{ .Values.ports.client }}
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: my-frontend-service
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.ports.client }}
      targetPort: {{ .Values.ports.client }}
  selector:
    app: my-frontend
